# Generated by Django 3.2.7 on 2021-11-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugInfo', '0002_auto_20211108_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buginfo',
            name='beyond_bug',
            field=models.IntegerField(blank=0, verbose_name='参数范围约束'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='datatype_bug',
            field=models.IntegerField(blank=0, verbose_name='数据类型约束'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='flow_bug',
            field=models.IntegerField(blank=0, verbose_name='流程异常处理'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='function_bug',
            field=models.IntegerField(blank=0, verbose_name='功能缺陷'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='interface_bug',
            field=models.IntegerField(blank=0, verbose_name='接口规范'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='law_bug',
            field=models.IntegerField(blank=0, verbose_name='非法字符约束'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='need_bug',
            field=models.IntegerField(blank=0, verbose_name='必选参数约束'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='other_bug',
            field=models.IntegerField(blank=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='buginfo',
            name='unique_bug',
            field=models.IntegerField(blank=0, verbose_name='参数唯一性约束'),
        ),
    ]
