# Generated by Django 3.2.7 on 2021-11-01 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=50, verbose_name='bug类型')),
                ('bug_count', models.IntegerField(verbose_name='bug数量')),
            ],
            options={
                'verbose_name': 'bug数量',
                'verbose_name_plural': 'bug数量',
                'db_table': 'bug数量',
                'ordering': ('bug_name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=2, verbose_name='性别')),
                ('id_no', models.CharField(max_length=30, unique=True, verbose_name='工号')),
                ('birth_date', models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0), verbose_name='出生年月')),
                ('experience', models.IntegerField(verbose_name='工作经验年限')),
                ('Level', models.CharField(max_length=50, verbose_name='岗位')),
                ('work_zone', models.CharField(max_length=50, verbose_name='部门')),
                ('skill', models.TextField(verbose_name='技术')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '简介',
                'verbose_name_plural': '简介',
                'db_table': '个人信息',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': '项目',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProgramInFo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=50, verbose_name='模块名称')),
                ('bugs_Any', models.IntegerField(blank=True, verbose_name='发现bug数量')),
                ('bugs_deal', models.IntegerField(blank=True, verbose_name='解决bug数量')),
                ('bugs_start_time', models.DateField(blank=True, verbose_name='发现bug起始时间')),
                ('bugs_end_time', models.DateField(blank=True, verbose_name='解决bug结束时间')),
                ('work_list', models.TextField(blank=True, verbose_name='主要成就')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_id', to='PersonInfo.person')),
                ('program', models.ManyToManyField(related_name='program_id', to='PersonInfo.Program')),
            ],
            options={
                'verbose_name': '业绩',
                'verbose_name_plural': '业绩',
                'db_table': '业绩',
                'ordering': ('module_name',),
            },
        ),
        migrations.CreateModel(
            name='PersonPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='PersonInfo.buginfo')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='PersonInfo.person')),
            ],
            options={
                'verbose_name': 'pie',
                'verbose_name_plural': 'pie',
                'db_table': 'pie',
                'ordering': ('bug_model',),
            },
        ),
    ]
