# Generated by Django 3.2.7 on 2021-11-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpie',
            name='bug_pie',
            field=models.CharField(blank=True, max_length=50, verbose_name='bug饼图'),
        ),
    ]
