# Generated by Django 3.2.7 on 2021-11-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonInfo', '0002_personpie_bug_pie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpie',
            name='bug_model',
        ),
        migrations.RemoveField(
            model_name='personpie',
            name='person',
        ),
        migrations.DeleteModel(
            name='BugInfo',
        ),
        migrations.DeleteModel(
            name='PersonPie',
        ),
    ]
