# Generated by Django 3.2.7 on 2021-11-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonInfo', '0003_auto_20211102_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_info', to='PersonInfo.person'),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='program',
            field=models.ManyToManyField(related_name='program_info', to='PersonInfo.Program'),
        ),
    ]
