# Generated by Django 3.2.7 on 2021-11-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonInfo', '0007_alter_programinfo_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='program_info', to='PersonInfo.Program'),
        ),
    ]
